apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.example.com
  # Syntax: accounts.<username>: <capabilities> and capabilities can be <apiKey > or <login>
  accounts.tester1: login
  accounts.tester2: login
  accounts.tester2: apiKey