---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment-green
  namespace: demo3
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx-green
  template:
    metadata:
      labels:
        app: nginx-green
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
        - name: nginx-container
          image: reg.fptcompute.com.vn/portal-new/demo-app:32
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment-blue
  namespace: demo3
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx-blue
  template:
    metadata:
      labels:
        app: nginx-blue
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: nginx-container
          image: reg.fptcompute.com.vn/portal-new/demo-app:35
          ports:
            - containerPort: 8080
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
---
apiVersion: v1
kind: Service
metadata:
  name: mywebservice
  namespace: demo3
spec:
  selector:
    app: nginx-green
  ports:
  - port: 81
    targetPort: 8080
  type: NodePort