---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment-green
  namespace: demo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx-green
  template:
    metadata:
      labels:
        app: nginx-green
    spec:
      imagePullSecrets:
        - registry-secret
      containers:
        - name: nginx-container
          image: reg.fptcompute.com.vn/portal-new/demo-app:32
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment-blue
  namespace: demo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx-blue
  template:
    metadata:
      labels:
        app: nginx-blue
    spec:
      imagePullSecrets:
        - registry-secret
      containers:
        - name: nginx-container
          image: reg.fptcompute.com.vn/portal-new/demo-app:35
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mywebservice
  namespace: demo
spec:
  selector:
    app: nginx-green
  ports:
  - port: 81
    targetPort: 8080
  type: NodePort