---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment-stable
  namespace: demo
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
        - name: nginx-container
          image: reg.fptcompute.com.vn/portal-new/demo-app:32
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment-canary
  namespace: demo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
        - name: nginx-container
          image: reg.fptcompute.com.vn/portal-new/demo-app:35
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mywebservice
  namespace: demo
spec:
  selector:
    app: nginx
  ports:
  - port: 81
    targetPort: 8080
  type: NodePort