apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app 
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      imagePullSecrets:
        - registry-secret
      containers:
      - image: reg.fptcompute.com.vn/portal-new/demo-app:32
        imagePullPolicy: Always
        name: hello-app
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
             path: /
             port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", "sleep 5"]
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app
  namespace: demo
spec:
  type: NodePort
  ports:
    - port: 81
      targetPort: 8080
  selector:
    app: hello-app