---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-fixed-strategy
  namespace: demo3
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fixed-strategy
  template:
    metadata:
      labels:
        app: fixed-strategy
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
        - name: nginx-container
          image: reg.fptcompute.com.vn/portal-new/demo-app:35
          ports:
            - containerPort: 8080
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName

---
apiVersion: v1
kind: Service
metadata:
  name: mywebservice
  namespace: demo3
spec:
  selector:
    app: fixed-strategy
  ports:
  - port: 81
    targetPort: 8080
  type: NodePort