---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-rolling-strategy
  namespace: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: rolling-strategy
  template:
    metadata:
      labels:
        app: rolling-strategy
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
        - name: nginx-container
          image: reg.fptcompute.com.vn/portal-new/demo-app:32
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "sleep 5"]

---
apiVersion: v1
kind: Service
metadata:
  name: mywebservice
  namespace: demo
spec:
  selector:
    app: rolling-strategy
  ports:
  - port: 81
    targetPort: 8080
  type: NodePort